### ISSUE TITLE
PROTOCOL PATH needs setting in .ioc-template

### ISSUE THREAD

**Issue by gilesknap** [epics-containers/ioc-template#45]
As discussed here  https://github.com/infn-epics/infn-epics-ioc/issues/3#issuecomment-2804620981.

The `services/.ioc-template/config/ioc.yaml` should include PROTOCOL PATH like this:

```YAML
# yaml-language-server: $schema=/epics/ibek-defs/ioc.schema.json

ioc_name: "{{  _global.get_env('IOC_NAME') }}"

description: DESCRIPTION GOES HERE

entities:
  - type: epics.EpicsEnvSet
    name: EPICS_TS_MIN_WEST
    value: "0"

  - type: epics.EpicsEnvSet
    name: STREAM_PROTOCOL_PATH
    value: /epics/runtime/protocol/

  - type: devIocStats.iocAdminSoft
    IOC: "{{ ioc_name | upper }}"
```
